### ISSUE TITLE
Tdk ada API users bisa mengakses gate tertentu (?)

### ISSUE THREAD

**Issue by irhammfadhil** [2019-pemrogramanberbasiskerangkakerja-h/secure-gate-system-kelompok1#2]
Kelompokku barusan ngetes api klp kalian, aku coba login ke salah satu gate kalian, jam yg diperbolehkan 06.00-23.00 (klo gak salah) tapi gak bisa tulisannya No Access (?), apa mungkin blm ada apinya atau gmn

![image](https://user-images.githubusercontent.com/33001097/57965336-245d4800-796d-11e9-8189-b67290b87522.png)

**Comment by jharisonn** [comment]
memang ga ada api access
